import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const handleAdd = async () => {
    const test = await fetch("/api/todos/add", {
      method: "POST",
      body: JSON.stringify({ text: "test" }),
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (test.ok) {
      console.log("success");
    }
    if (test.status === 401) {
      console.log("error");
    }
  };

  const handleEdit = async () => {
    const test = await fetch("/api/todos/edit", {
      method: "POST",
      body: JSON.stringify({ id: 1, text: "edit this" }),
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (test.ok) {
      console.log("success");
    }
    if (test.status === 401) {
      console.log("error");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-5xl mx-auto p-10 space-y-4">
        <button></button>
        <h1 className="text-3xl font-bold">Yucaba Test</h1>
        <div className="space-y-4">
          <p>
            Please use this repo to construct a TODO app with Next.js and
            Serverless functions.
          </p>
          <p>
            Please use <span className="text-blue-600">Tailwind UI</span>{" "}
            components to construct the following application.
          </p>
          <p>
            You can add yourself to my tailwind UI component account by
            following this link:{" "}
            <a
              className="text-blue-500 underline cursor-pointer"
              target="_blank"
              href="https://tailwindui.com/teams/invite/1mpK8w8oKETlbsRqtDcyky2V1Yxy2DHj"
            >
              Tailwind UI
            </a>
          </p>
          <p>
            Please install and use the{" "}
            <span className="text-blue-600">React Query</span> library to manage
            your endpoints and state.
          </p>
          <p>
            The following endpoints/serverless functions can be used to create
            your todo app. You can find them in the api directory of this repo.
          </p>
          <ul className="my-4">
            <li>
              /api/todos/add payload is{" "}
              {`{
                  text: string
                }`}
            </li>
            <li>
              /api/todos/delete payload is{" "}
              {`{
                  id: number
                }`}
            </li>
            <li>
              /api/todos/edit payload is{" "}
              {`{
                  id: number,
                  text: string
                }`}
            </li>
            <li>/api/todos/get - no payload needed</li>
            <li>
              ** All endpoints are using the <strong>POST</strong> method
            </li>
          </ul>
          <p>
            Please spend up to 3 hours on the project. If you have any questions
            email me at dan@yucaba.com
          </p>
          <button onClick={handleAdd} className="p-4 border-gray-200 border">
            Sample Add todo endpoint called here
          </button>
          <button onClick={handleEdit} className="p-4 border-gray-200 border">
            Sample Edit todo endpoint called here
          </button>
        </div>
      </main>
    </>
  );
}
